### ISSUE TITLE
Doesn't detect new Wingman map mode

### ISSUE THREAD

**Issue by XBase-xOR** [rakijah/CSGSI#18]
After entering a Wingman game accessing the Map property fails with an exception:

System.ArgumentException: "Requested value 'scrimcomp2v2' was not found"
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at CSGSI.Nodes.NodeBase.GetEnum[T](String Name)
   at CSGSI.Nodes.MapNode..ctor(String JSON)
   at CSGSI.GameState.get_Map()

This is probably due to the new map mode scrimcomp2v2 for Wingman missing from the MapMode enum.

I read something about a new scrimcomp5v5 map mode too but I don't know what exactly that is.

**Comment by XBase-xOR** [comment]
Added the value to the enum and changed nothing else, seems to be sufficient, works flawlessly with Wingman now.

**Comment by rakijah** [comment]
Hey, thanks for letting me know, I hadn't tried that myself yet.

I have added ScrimComp2v2 to the MapMode enum. Holding off from adding ScrimComp5v5 for now since the only information I could find on that seemed to be unrelated to GSI.
New version should be available as a NuGet package shortly.

**Comment by XBase-xOR** [comment]
Nice, thanks for the quick response!
